xrdb ~/.Xresources

export GTK2_RC_FILES=$HOME/.gtkrc-2.0
export `dbus-launch`
export PATH="$PATH:$HOME/.0desk/bin"
export BROWSER=exo-open

monitors auto

[[ -f ~/.fehbg ]] && (sh ~/.fehbg &)

tint2 &
nm-applet &
volumeicon &
batti &
dropbox &

autolock &

exec openbox
